config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  resources :users, only: [:new, :create, :show] do
    resources :workouts, only: [:index, :show]
  end
  resources :trainers, only:[:new, :create, :index, :show] do
    resources :workouts, only: [:index, :new, :create, :show, :edit, :update]
  end
  resources :workouts, only: [:index, :show, :create, :edit, :update]
  delete 'workout/:id/delete', to: 'workouts#destroy', as: :delete
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/welcome', to: 'sessions#welcome'
  delete 'session/delete', to: 'sessions#delete', as: :logout 
  get "/auth/github/callback" => "sessions#create_from_github"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    has_many :workouts
    has_many :users, :through => :workouts

    def most_difficult_workouts
        self.workouts.where ('difficulty >= 4')
    end

end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: true
    validates :password, length: { in: 6..20 }
    has_secure_password
    has_many :workouts
    has_many :trainers, :through => :workouts

    def add_to_workouts
      self.workouts <<@workout.id
    end

    def self.create_with_omniauth(auth)
        create! do |user|
          user.provider = auth["provider"]
          user.uid = auth["uid"]
          user.name = auth["info"]["name"]
        end
    end
end

app/models/workout.rb
class Workout < ApplicationRecord
    validates :title, presence: {message: "Workout must have a title"}
    validates :length, presence: {message: "Enter workout length in minutes"}
    validates :description, presence: {message: "Provide a description for this workout"}
    validates :difficulty, presence: {message: "Provide a difficulty level for this workout"}
    belongs_to :trainer
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
        protect_from_forgery with: :exception
        before_action :require_login
        #helper_method :all
      # private
    
      # def require_login
      #   redirect_to 'sessions/welcome' unless user_is_authenticated
      # end
    
      # def user_is_authenticated
      #   !current_user.nil?
      # end
    
      # def current_user
      #   User.find_by(id: session[:user_id])
      # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include ApplicationHelper
    skip_before_action :require_login, only: [:new, :create, :welcome]

    def welcome
    end
  
    def new
      @user = User.new
      render 'login'
    end
  
    def create
      @user = User.find_by(username: params[:session][:username])
      if @user && @user.authenticate(params[:session][:password])
         session[:user_id] = @user.id
         flash[:notice] = "Logged in successfully"
         redirect_to user_path(@user)
      else
          flash[:alert] = "Invalid username/password"
          redirect_to new_user_path
      end
   end

   def create_from_github
    binding.pry
    pp request.env['omniauth.auth']
    session[:name] = request.env['omniauth.auth']['info']['nickname']
    session[:omniauth_data] = request.env['omniauth.auth']
    redirect_to root_path


    #user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)     
    #session[:user_id] = user.id     redirect_to root_path, :notice => "Signed in!"
    end

  
    def delete
      session[:user_id] = nil
      flash[:notice] = "You have been logged out"
      redirect_to root_path
    end

    private

    def auth
      request.env['omniauth.auth']
    end
  end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
    include ApplicationHelper
    def index
        @trainers = Trainer.all
    end

    def show
        @trainer = Trainer.find_by(id: params[:id])
    end

    def new
       @trainer = Trainer.new 
    end

    def create
        trainer = Trainer.create(trainer_params)
        redirect_to trainer_path(trainer)
    end

    private
    def trainer_params
        params.require(:trainer).permit(
            :name,
            :bio
        )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include ApplicationHelper
    before_action :require_login
    skip_before_action :require_login, only: [:new, :create]
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        render 'new'
      end
    end
  
    def show
      @user = User.find_by(id: params[:id])
    end
  
    private
  
    def user_params
        params.require(:user).permit(:username, :password)
    end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  include ApplicationHelper
    def index
      @trainer = Trainer.find_by(id: params[:trainer_id])
      if @trainer
        @workouts = @trainer.workouts # this will load only the trainer's workours
      else
        @workouts = Workout.all #loads all workouts
      end
    end

    def show
        @workout = Workout.find_by(id: params[:id])
    end
    
      def new
        @workout = Workout.new
        @workout.trainer = Trainer.find_by(id: params[:trainer_id])
      end

      def create
        workout = Workout.new(workout_params)
        workout.user = current_user
        workout.trainer = Trainer.find_by(id: params[:workout][:trainer_id])
        if workout.save
          flash[:notice] = "Workout created successfully."
          redirect_to workout_path(workout)
        else
          redirect_to new_trainer_workout_path(params[:workout][:trainer_id])
        end
      end

      def edit
        @workout = Workout.find_by(id: params[:id])
      end

      def update
        workout = Workout.find_by(id: params[:id])
        workout.update(workout_params)
        if workout.save
          flash[:notice] = "Workout updated successfully."
        redirect_to workout_path(workout)
        else
          flash[:alert] = "There was a problem updating the workout."
          render 'edit'
        end
      end

      def destroy
        Workout.find(params[:id]).destroy
        redirect_to workouts_path
      end


      private

    def workout_params
      params.require(:workout).permit(
        :title,
        :description,
        :length,
        :difficulty,
        :user_id,
        :trainer_id
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def require_login
        redirect_to 'sessions/welcome' unless user_is_authenticated
    end
    
      def user_is_authenticated
        !current_user.nil?
      end
    
      def current_user
        User.find_by(id: session[:user_id])
      end
end

app/helpers/user_helper.rb
module UserHelper
    def require_login
        redirect_to 'sessions/welcome' unless apples
    end
    
    def apples
        !current_user.nil?
    end
    
    def current_user
        User.find_by(id: session[:user_id])
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuddyBody</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'sessions/navbar' %>

    <% flash.each do |name, msg| %>
      <div class="custom-alert">
      <%= msg %>
      </div>
    <%end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/trainers/index.html.erb
<div class="text-center">
<h1> Buddy Boddy's Trainers! </h1>
</div>
<br>
<%@trainers.each do |trainer|%>
    <%=trainer.name%>
    <%=link_to "Trainer's Bio", trainer_path(trainer) %>
    <% end %><br>

<%= link_to "New Trainer", 'trainers/new'%>

app/views/trainers/new.html.erb
<h3>Trainer Form</h3>

<%= form_for(@trainer) do |f| %>
  <label>Trainer name:</label><br>
  <%= f.text_field :name %><br>

  <label>Trainer Bio</label><br>
  <%= f.text_area :bio, :size => 100 %><br>

  <%= f.submit %>
<% end %>

app/views/trainers/show.html.erb
<div class="jumbotron text-center">
<h2> <%= @trainer.name %> </h2>
</div>
<br>
<div class="text-center">
<h3> Bio </h3>
<p class="font-italic"> <%= @trainer.bio%> </p>
</div>
<br>
<%= link_to "#{@trainer.name}'s workouts", trainer_workouts_path(@trainer) %><br>
<%= link_to "New workout with #{@trainer.name}", new_trainer_workout_path(@trainer) %><br>
<div class="text-center">
<h3> <%= "#{@trainer.name}'s most challenging workouts" %> </h3>
</div>
<div class="text-center">
<% @trainer.most_difficult_workouts.each do |workout| %>
<ul>
    <%= link_to "#{workout.title}", workout_path(workout) %>
</ul>    
<%end%>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> Sign Up for Buddy Boddy! </h1>	
	<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>

app/views/users/show.html.erb
<div class="jumbotron text-center">
<h2>Hello, <%= current_user.username %></h2>
</div>

<div class="text-center">
<h3>Your Workouts:</h3>
</div>

<div class="text-center">
<% @user.workouts.each do |workout| %>
<ul>
    <%= link_to "#{workout.title}", workout_path(workout) %>
</ul>    
<%end%>
</div>


<%= link_to "Buddy Body's Workouts", user_workouts_path(current_user) %><br>
<%= link_to "Buddy Body's Trainers", trainers_path%><br>
<%= button_to "Logout", logout_path, method: :delete%>

app/views/workouts/_form.html.erb
<%= form_for(object) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being created:
      </h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(object) do |f|%>

<%= f.label :title%><br>
<%= f.text_field :title, placeholder: :title %>
<br>
<%= f.label :length%><br> 
<%= f.text_field :length, placeholder: :length_in_minutes %>
<br>
<%= f.label :difficulty%><br>
<%= f.text_field :difficulty, placeholder: :rating_1_to_5 %>
<br>
<%= f.label :description%><br>
<%= f.text_area :description, placeholder: :workout_descriprion %>
<br>
<%= f.hidden_field :user_id %><br />
<%= f.hidden_field :trainer_id %><br />
<%= f.submit %>
<% end %>
<%end%>

app/views/workouts/edit.html.erb
<div class="text-center">
<h1>Edit Workout</h1>
</div>

<% if @workout.errors.any? %>
    <h2>The following errors prevented the workout from being saved</h2>
    <ul>
        <% @workout.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end%>

<%= form_with(model: @workout, local: true) do |f| %>

<%= f.label :title%><br>
<%= f.text_field :title, placeholder: :title %>
<br>
<%= f.label :length%><br> 
<%= f.text_field :length, placeholder: :length_in_minutes %>
<br>
<%= f.label :difficulty%><br>
<%= f.text_field :difficulty, placeholder: :rating_1_to_5 %>
<br>
<%= f.label :description%><br>
<%= f.text_area :description, placeholder: :workout_descriprion %>
<br>
<%= f.hidden_field :user_id %><br />
<%= f.hidden_field :trainer_id %><br />
<%= f.submit %>

<% end %>

app/views/workouts/index.html.erb
<div class="text-center">
<h1>Workouts</h1>
</div>
<ul>
<%@workouts.each do |workout|%>
    <h3><%=workout.title%></h3> <br>
    <p>Length - <%=workout.length%> minutes </p> <br>
    <p> Difficulty Level - <%=workout.difficulty%> </p> <br>
    <%=link_to "Workout Description", workout_path(workout) %><br>
    <% end %>
    </ul>

app/views/workouts/new.html.erb
<div class="text-center">
<h1>New Workout</h1>
</div>
<%= render partial: 'form', locals: { object: @workout } %>

app/views/workouts/show.html.erb
<div class="center">

  <div class="info">
    <p><strong>Title:</strong> <%= @workout.title %></p>
    <p><strong>Workout Length:</strong> <%= @workout.length %> minutes</p>
    <p><strong>Workout Difficulty:</strong> <%= @workout.difficulty %></p>
    <p><strong>Description:</strong> <%=@workout.description %></p>
    <p><strong>Instructor:</strong> <%= link_to "#{@workout.trainer.name}", trainer_path(@workout.trainer) %></p>
      <%= form_for @workout do |f| %>
        <%= f.hidden_field :user_id %><br />
        <%= f.hidden_field :trainer_id %><br />
        <%= f.submit "Add To My Workouts", class:"btn btn-light" %>
      <% end %>
  </div>

</div>
  <%= button_to "Edit Workout", edit_workout_path(@workout) %>
  <%= button_to "Remove workout", delete_path(@workout), method: :delete %>